import { createSlice } from '@reduxjs/toolkit';
import { AppConfig } from './interfaces/AppConfig';
import UniqueValueRenderer from '@arcgis/core/renderers/UniqueValueRenderer';

// The initial GATE application State
const initialState: AppConfig = {
    portalConfigItemId: '',
    portalUrl: '',
    oauthAppId: '',
    elevationUrl: '',
    classificationBanner: '',
    areClassificationMarkingsFake: true,
    version: '',
    defaultWebMapId: '',
    defaultWebSceneId: '',
    symbolItemId: '',
    emptyWebSceneTemplateId: '',
    outputDebugMessages: true,
    panningSpeed: 6,
    defaultElevationMode: '',
    immadVersion: '3.x',
    flashGraphicColor: [255, 0, 0],
    gate: {
        gateAdminGroupId: '',
        analystComments: '',
        landingPageData: '',
        regionSummary: '',
        j2Assessment: '',
        regionsFClassGuid: '',
        landingPageFClassGuid: '',
        j2SummaryFClassGuid: '',
        j2SummaryFields: [],
        analystCommentsFClassGuid: '',
        calendarGuid: '',
        sourcesGuid: '',
        queryForGateApplication: '',
        watchConLabel: '',
        lastUpdatedFieldName: 'last_edited_date',
        executeCountQueriesSequentially: false,
        exercise: {
            exRegionsFClassGuid: '',
            exLandingPageFClassGuid: '',
            exJ2SummaryFClassGuid: '',
            exAnalystCommentsFClassGuid: '',
            exCalendarGuid: '',
            exSourcesGuid: '',
        },
        dynamicLayerServiceId: '',
        dynamicLayerServicePollIntervalMins: 1,
        dynamicLayerServiceDefaultExpirationTimeHrs: 24,
        dynamicFeatureServiceTemplate: {}, // Provide actual structure here as needed
        dynamicLayerServiceTemplate: {}, // Provide actual structure here as needed
    },
    tags: {
        webmap: '',
        webscene: '',
        group: '',
        user: '',
        webTool: '',
        gpTool: '',
        dataFeed: '',
        mission: '',
        missionData: '',
        application: '',
        tacticalGrid: '',
        exerciseFClass: '',
    },
    countWidgetRowColors: ['silver', 'darkgray'],
    types: {
        webMappingApplication: '',
        application: '',
        featureService: '',
        webScene: '',
        geoprocessingService: '',
        webTool: '',
        webMap: '',
    },
    typekeywords: {
        immadMission: '',
        gateMission: '',
        gateExercise: '',
        immadExercise: '',
    },
    smart: {
        getDashboardDataUrl: '',
        getSystemsJsonUrl: '',
        recordUploadUrl: '',
        getRecordByIdUrl: '',
        useLiveDashboards: true,
        runningInCIGT: true,
        recordActive: false,
        smartRecordUploadRecordIdsParam: '',
        recordActiveFieldName: '',
        testDashboardId: '',
        smartRecordVersionFieldName: '',
        smartRadiusFieldName: '',
        smartSystemIdFieldName: '',
        smartGroupIdFieldName: '',
        smartDashboardFieldName: '',
        smartRecordIdFieldName: '',
        smartRecordTypeFieldName: '',
        smartUpdateTrackingIdKey: '',
        smartRecordStatusFromFieldName: '',
        smartRecordEventDateFieldName: '',
        smartFormSystemCheckboxLabelFieldName: '',
        smartRecordPathFieldName: '',
        smartGUID: '',
        smartSystemRecordType: '',
        smartGroupRecordType: '',
        smartLastUpdatedByFieldName: '',
        smartLastUpdatedDateFieldName: '',
        useXMLHttpPost: true,
        useEncodeURIComponent: false,
        updateOnVersionConflict: true,
        errorOnVersionConflict: true,
        showErrorOnRadiusCalcFailure: true,
        nullableFields: [],
        smartFieldsToNotUpdateWhenUpdatingTheGroup: [],
        smartLocationFieldNames: [],
        smartExtraSystemFieldsToAddToForm: [],
        smartUpdatePostParams: [],
        mappableFields: [],
        fetchPostParamsFromConfig: {
            method: 'POST',
            mode: 'cors',
            body: {},
            headers: { 'Content-Type': 'application/x-www-form-urlencoded, charset=UTF-8' },
        },
        fetchGetParamsFromConfig: {
            method: 'GET',
            mode: 'cors',
            headers: { 'Content-Type': 'application/json' },
        },
        fieldsWithNumericValues: [],
    },
    rks: {
        integerFields: [],
        testSearchUrl: '',
        entityMetaDataUrl: '',
        detailSearchUrl: '',
        entityDetailMetaDataUrl: '',
        operatorGroupSearchUrl: '',
        runDebug: true,
        detailsSearchMaxRecordCount: 10000,
        entityDetailsSearch: {
            datasets: [],
            entityId: [],
            detailType: [],
            elementType: [],
            searchOptions: {
                sort: '',
                order: '',
                scrollId: '',
                from: 0,
                size: 300,
            },
        },
    },
    roles: {
        tag: '',
        admin: {
            tag: '',
            privileges: [],
        },
        missionManager: {
            tag: '',
            privileges: [],
        },
        analyst: {
            tag: '',
            privileges: [],
        },
    },
    analyticCatalog: {
        tool_tag: [],
    },
    portalItemList: {
        maxRecordCountWhenPaging: 0,
        classifications: [{ name: '', backgroundColor: '', textColor: '' }],
    },
    remoteView: {
        wsUri: '',
        metadataUrl: '',
        pollDelay: 0,
    },
    dataFeed: {
        mainRestUrl: '',
        queryTypes: [
            {
                name: '',
                value: '',
                url: '',
                timeInfo: { startField: '', endField: '' } as __esri.TimeInfo,
                geoJsonData: [],
                polygonStyle: { stroke: '#00ffff', strokeWidth: 1, fill: '#00ffff', fillOpacity: 0.5 },
                lineStyle: { stroke: '#ff69b4', strokeWidth: 1 },
            },
        ],
        groupNames: [''],
    },
    settings: {
        disableSceneLighting: false,
        disableAtmosphere: true,
    },
    sketch: {
        defaultSymbol: {
            size: 10,
            color: [255, 255, 255],
            outline: { color: [0, 0, 0], width: 1 },
        },
    },
    doctrinalTemplate: {
        renderer: {} as UniqueValueRenderer,
    },
    remapUrls: true,
    urlRemapRules: [{ url: '', remapUrl: '' }],
    refreshIntervalsInMinutes: [],
    tacticalGrid: {
        dataLayerId: '',
        statusField: '',
        recentHighlightTimeoutInMinutes: 1,
        refreshIntervalInSeconds: 100,
        stratLeadCompareField: '',
        stratLeadExpirationUnitLabel: '',
        zoomViewScale: 1500000,
        stratLeadExpiration: [],
        stratLeadMaxExpiration: 100,
        maximumSelectedRowsAllowed: 10,
        defaultFieldMappings: [],
        quickFilters: [],
    },
    layerEllipse: {
        semi_major_fields: [],
        semi_minor_fields: [],
        azimuth_fields: [],
    },
    analyticsSettings: [],
    search: {
        includeGeocoder: false,
        name: '',
        allPlaceholder: '',
        url: '',
    },
    opsClocks: [],
    missionMessages: [],
};

// Slice for application state management
export const applicationSlice = createSlice({
    name: 'application',
    initialState,
    reducers: {
        setWholeApplicationConfig: (state, action) => ({ ...state, ...action.payload }),
    },
});

export const { setWholeApplicationConfig } = applicationSlice.actions;

export default applicationSlice.reducer;
